import { execFile } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

export type ProjectEntry = { repo: string; localPath?: string; purpose: string };
export type ProjectStatus = ProjectEntry & { branch?: string; openPrs?: string; staleBranches?: string; planStatus?: string; monitorHealth?: string };

function expandHome(path: string) {
  return path.replace(/^~(?=\/|$)/, homedir());
}

export function parseProjectsIndex(markdown: string): ProjectEntry[] {
  const entries: ProjectEntry[] = [];
  for (const line of markdown.split('\n')) {
    const cells = line.trim().split('|').slice(1, -1).map((cell) => cell.trim());
    if (cells.length < 3 || /^-+$/.test(cells[0]) || cells[0] === 'Repo') continue;
    const repo = cells[0].match(/\[([^\]]+)\]/)?.[1] || cells[0];
    if (!repo.includes('/')) continue;
    const localRaw = cells[1].replace(/`/g, '').trim();
    entries.push({ repo, localPath: localRaw && localRaw !== '—' ? expandHome(localRaw) : undefined, purpose: cells[2] || '' });
  }
  return entries;
}

export function parsePlanReadme(markdown: string): Map<string, string> {
  const statuses = new Map<string, string>();
  for (const line of markdown.split('\n')) {
    const cells = line.trim().split('|').slice(1, -1).map((cell) => cell.trim());
    if (cells.length < 2 || /^-+$/.test(cells[0])) continue;
    const text = cells.join(' ').toLowerCase();
    const repo = text.match(/kyleboas\/[a-z0-9._-]+/)?.[0];
    if (repo) statuses.set(repo, cells.join(' - '));
  }
  return statuses;
}

async function git(cwd: string, args: string[]) {
  try {
    const { stdout } = await execFileAsync('git', args, { cwd, timeout: 3000, maxBuffer: 200_000 });
    return stdout.trim();
  } catch {
    return '';
  }
}

async function repoStatus(entry: ProjectEntry, planStatuses: Map<string, string>): Promise<ProjectStatus> {
  const status: ProjectStatus = { ...entry, planStatus: planStatuses.get(entry.repo) || 'none', monitorHealth: 'unknown' };
  if (!entry.localPath) return status;
  status.branch = await git(entry.localPath, ['branch', '--show-current']) || 'unknown';
  const branches = (await git(entry.localPath, ['for-each-ref', '--format=%(refname:short) %(committerdate:unix)', 'refs/heads'])).split('\n').filter(Boolean);
  status.staleBranches = String(branches.filter((line) => {
    const unix = Number(line.match(/\s(\d+)$/)?.[1] || 0);
    return unix > 0 && Date.now() - unix * 1000 > 30 * 24 * 60 * 60_000;
  }).length);
  status.openPrs = 'not checked';
  return status;
}

export function renderProjectsStatus(statuses: ProjectStatus[], generatedAt = new Date()) {
  const rows = statuses.map((item) => `| ${item.repo} | ${item.localPath || '—'} | ${item.branch || '—'} | ${item.openPrs || '—'} | ${item.staleBranches || '—'} | ${item.monitorHealth || '—'} | ${(item.planStatus || 'none').replace(/\|/g, '/')} | ${item.purpose.replace(/\|/g, '/')} |`);
  return [
    '# Projects Status',
    '',
    '<!-- generated by Mi; do not hand-edit -->',
    '',
    `Generated: ${generatedAt.toISOString()}`,
    '',
    '| Repo | Local Path | Branch | Open PRs | Stale Branches | Monitor Health | Plan Status | Purpose |',
    '|---|---|---|---:|---:|---|---|---|',
    ...rows,
    '',
  ].join('\n');
}

export async function generateProjectsStatus(options: { projectsPath?: string; plansReadmePath?: string; outputPath?: string } = {}) {
  const projectsPath = options.projectsPath || join(homedir(), 'pi-docs', 'PROJECTS.md');
  const plansReadmePath = options.plansReadmePath || join(homedir(), 'code', 'plans', 'README.md');
  const outputPath = options.outputPath || join(homedir(), 'pi-docs', 'projects-status.md');
  const projects = parseProjectsIndex(await readFile(projectsPath, 'utf8'));
  const planStatuses = parsePlanReadme(await readFile(plansReadmePath, 'utf8').catch(() => ''));
  const statuses = await Promise.all(projects.map((entry) => repoStatus(entry, planStatuses)));
  const markdown = renderProjectsStatus(statuses);
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, markdown);
  return { outputPath, projects: statuses.length, markdown };
}
